version: 2

jobs:
  build:
    working_directory: ~/ci_geom2d
    
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    
    steps:
      - checkout
      - run: ./gradlew build
      - run: ./gradlew test
